-- COLORS --
BOTCHED.DEVCONFIG.Colors = { 
    Bronze = Color( 176, 122, 60 ),
    Silver = Color( 165, 165, 165 ),
    Gold = Color( 222, 175, 7 ),
    Diamond = Color( 0, 255, 233 ),

    Red = Color( 231, 76, 60 ),
    DarkRed = Color( 192, 57, 43 ),

    Blue = Color( 52, 152, 219 ),
    DarkBlue = Color( 41, 128, 185 ),

    Orange = Color( 243, 156, 18 ),
    DarkOrange = Color( 230, 126, 34 )
}

-- ENTITY SAVING --
BOTCHED.DEVCONFIG.EntityTypes = BOTCHED.DEVCONFIG.EntityTypes or {}
BOTCHED.DEVCONFIG.EntityTypes["botched_menu_npc"] = { 
    GetDataFunc = function( ent ) 
        return ent:GetMenuType() .. ";" .. ent:GetNPCKey()
    end,
    SetDataFunc = function( ent, data ) 
        local data = string.Explode( ";", data )
        ent:SetMenuType( data[1] )
        ent:SetNPCKey( tonumber( data[2] ) )
    end
}

-- KEY BINDS --
BOTCHED.DEVCONFIG.KeyBinds = {
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Numpad 0",
    "Numpad 1",
    "Numpad 2",
    "Numpad 3",
    "Numpad 4",
    "Numpad 5",
    "Numpad 6",
    "Numpad 7",
    "Numpad 8",
    "Numpad 0",
    "Numpad /",
    "Numpad *",
    "Numpad -",
    "Numpad +",
    "Numpad Enter",
    "Numpad .",
    "(",
    ")",
    ";",
    "'",
    "`",
    ",",
    ".",
    "/",
    [[\]],
    "-",
    "=",
    "Enter",
    "Space",
    "Backspace",
    "Tab",
    "Capslock",
    "Numlock",
    "Escape",
    "Scrolllock",
    "Insert",
    "Delete",
    "Home",
    "End",
    "Pageup",
    "Pagedown",
    "Break",
    "Left Shift",
    "Right Shift",
    "Alt",
    "Right Alt",
    "Left Control",
    "Right Control",
    "Left Windows",
    "Right Windows",
    "App",
    "Up",
    "Left",
    "Down",
    "Right",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "Capslock Toggle",
    "Numlock Toggle",
    "Last",
    "Count"
}